apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    nextcloud.yaml: ENC[AES256_GCM,data:PRjEjiGGPtF7fPiAefwRPf1dPq+rZSTA9X8ft7j7+tia5/s8H3QpS+3PWvHXb1ZuKxnxl8gMsAj0RjLUC6d01q73OXzJED3f9i74zarYKIU+q0VhOtJ0QRhu+3UAgA3gHjMX8KavWfjJHBu+Az8ExaHG8fjef0LFujzMVuJWvBxYBlJjD7sESSzv2XDBJiesfOdHYYFXeioQYO25VKGPCXraNmBjeW0FkeZl8FTlCnkpEhuoJiSzUxpKSLzjHMzqz9+8Ksof0kug/RTLs9YaNMTdelDV59KReFP9YUBk3w==,iv:I6Q7T7+SAnl8FhtmLHy6U8DYm11QmAUCRV/6/j0aTas=,tag:zbk1KNu9IQwiXUMHJQKaWQ==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:Jzb6gIQGGjesv/wrwdFJqE5oBHetfC5YSVTxvKzWoHg3rFM0KQWLGE2fNIS+H8uW+ly3FzLVUD3jOpvRi2QjaDA7Dy3D7DEt40olUIt9zW6QPD/6ghwBaKqhqMzwIq8RhEG2JnfndurO9Ma+sfAYng==,iv:KB90HM99sBE0hYSh/T4lNibMlKhs1UBGg4Gk73ybO/w=,tag:Ou5axKcA1TTMJhIVdnGt5g==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T04:40:41Z"
    mac: ENC[AES256_GCM,data:W3Sssng+sqblsd304dcv9wMl6b9LT1IPnK5l6Dp4uUc3Xm3KDXX+Z6EMJdhBKekdZBDfN20tjhCKt9tQk/52RrHmjYB/0yzH50CMtNALNv0uIkJmfvfx7bQzXcU/+f91lXXG8vyGP4ZDKor2V+9XG1jXDt51rmM7mXUsQrTG/Tc=,iv:t20qduCz3g7lp1bN++tO/MdTrULFXywcIS+RjrcQE5Y=,tag:gUNJnNAWHGUO58hwT8CWwA==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
