apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: ${MY_NAMESPACE}-db-app-fix
stringData:
    username: ENC[AES256_GCM,data:DmXt,iv:mauV2LeVwXxFqdqa+Pw4wevJ2J94qA4GZg5gIrN6SwE=,tag:Oel8ty4Rdwvq/weYWQBY2w==,type:str]
    password: ENC[AES256_GCM,data:PPjEDrWZnMmc0DpIMPr5b9hVEWsyjDjz2mijofGw8EScuSCSF8jM70qAW3+AVZ96+OX9mL0RhvdFfnZBAE9heA==,iv:x3N2hD7m5qosoR5FpuMUQh6K2NwG70MsRTrnFnLNqX0=,tag:WMaZdClQEWZCr158XOGVXg==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T13:02:08Z"
    mac: ENC[AES256_GCM,data:RUmdUo6JrbIHMg/GS46n/fWTcqFyr/o7KBcUZRIRej/pxX1dFgoDSpJQ9TV5b8Rwq4zkb77Dni5jVxB/Hl339Zc34SQ1oXlqd8geBXnM9PoKt60gi2OOpHkL4EWAerGrSRapkXdkr9rKaqiDtWqKaxVPYImNk/SqvBHR2ZOHqfc=,iv:QUIHWskTVLarTJJPo4SfG7YjdDdPgdubrzyjwFm3VhE=,tag:SZ8d2uJqiPexc4J3k97UHg==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
