apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: localnet
spec:
  namespaceSelector:
    matchLabels:
      secondary.network: localnet
  network:
    topology: Localnet
    localnet:
      role: Secondary
      subnets:
      - "192.168.6.64/26"
      physicalNetworkName: br-ex