apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cluster-udn-civil-leopard
spec:
  namespaceSelector:
    matchLabels:
      secondary.network: localnet
  network:
    topology: Layer2
    localnet:
      role: Secondary
      subnets:
      - "192.168.0.0/19"
      physicalNetworkName: br-ex