kind: Secret
apiVersion: v1
metadata:
    name: authentik-config
stringData:
    values.yaml: ENC[AES256_GCM,data:8RYiwevEUpwpGFnWlPt9y2XaotqizVvGneJdP5AjSIJK8fVlMInoIyYkyuIjYNfMEIDaQ7sJJcg9Lo9xc8zZclbTr2qXfuc5lkdBemS1s+G53+eZaNuZSLBy7KB3Fc1F+8MVGp3I/JMVbcgaXfLIYl5Aeus3D8LUGOd9Q4kC+ySRJWhWjzSHj2BPZp77VYnbPLSbC20mvEtzLIucwjtLLxUTc1wM/On73bYek1Wmu0GyNGZhRMy9N4g5+1bHjXsXfTGD61HLpnW9Ckt1llg9JHeCXvbw9njpZOPX9MYUy5xIdCi5X1XqotUKXRs3jv4=,iv:916bfnN8bYZL5pxDi0/yzJzW6e8DTI+ZkBkJyTnpAnE=,tag:J6er4wnFIVCx9lImQuP8qg==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T17:50:26Z"
    mac: ENC[AES256_GCM,data:+tiGFkvpJ/EVR3W0FBx8+Lc4O5r5GxidHESO2Eb5rbS+Mn/cN/+PJUCh5ba2p37BLohpWjGkfg08jmnPLqu3UnLb/HX6Y0RvwdsNTUasK3G+K6Wch/k59CC1UGbZOTsKxixCgQN43d0mZaDaRJDkvTVfj+F/bagGBRsfi9rM0JQ=,iv:8fWOOWR4waQxZkS/kPq239MmYr/fBEFIfTxvC2QUbFk=,tag:22XGLx8Wz2CVLEMM6bKGyQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
