kind: Secret
apiVersion: v1
metadata:
    name: authentik-config
stringData:
    values.yaml: ENC[AES256_GCM,data:vwgVd+m1hhtFRsCIgIhQZyRgxQlvrEBAcWWi0Y/TDA8vcrUKPWS2tCwtme4b89SwaDeUPnf780AEEdeKHGnohYrsUu8zTWyDHS7j7SVEy+lgoc4zU9rUPdTukX4Tur4VjlltxVIQRDQI0dZpT5Q69TGBtWbKeewCrF8YbpQSl643NuPA+g1tlZFIGcPWlDtUEmoeR08lL7S3Yhn1u6Vn99uhlcrzDo3exFnkbAF/g6NcNoDxdEVoLm7nnAorN+840vqls1A0Q6TPRcXdDyN4IXPm8xZrsBeSYf4Mrf48MIentpA1HP84gx3e1pRkYqukgXiEyi0DJsSTe2vLb6LQFep+662k+W/6N2C4y1rCuZGfb/6FEDgePAaBBWAGK8qKk7dM69+SfbViOWZs2oDGhLG+r72xmZimVm9aiRs+GMlz1pLrHhv4aUciMMPJZOgjO8YSgP3kj+gukHjYi8t7FHOLdJLO2QiuTf5ERRnMguCETkQm4GEM2JsTW18=,iv:PZPLRUH/NIo88lXsUhUoudKoerT47GjyNyakMhx7IlI=,tag:kG1lQTI8w7/Fs1sPTysrfg==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T21:02:49Z"
    mac: ENC[AES256_GCM,data:7PYVxbXS7z/Dobv84jXlOSG5yoIaEEUO7csV6znmVM/VGYfw7AIagnGVEp/A9CMP25lhoLiIlUXO4mD+I4p85IOi4hE/cK+sl9V1VdogQjJWAUWHUuz1jozPbBaXe1BSVU0QM0IhB5rHWg0Xm1dwPsrOkOgOkBudrgqI5wrTmeA=,iv:Jh3TDszbn4ZZ01zth8Q2j71wlOS/tFK/YHVo6ZgWphA=,tag:G+IvJmJgC/5XrS7SbQj7jA==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
