kind: Secret
apiVersion: v1
metadata:
    name: authentik-config
stringData:
    values.yaml: ENC[AES256_GCM,data:wGflmVkqvIcCXQHdEOT03u7MHeLtAtjfW6VLSYMun8qQFInYyOhsGoi3RpAs4jl1Bm4jtfwNW9FGosyFqizMdiU6/rAWTASWjsmO4EIyQIhTMaF4xKSh42S0v580hxsGFFc1ikLzCjebktSnIWyUO0kD/mGLjGFdpXWy4gI5b3oDg8u6KYO+7fc03vLYxsIC3NSK+JLTX21i4OonW9bQZ48b2ImMCbi3rDISi/axpcYqT/29jjj5KkGqnOJ+WOUnnVeChxvbPhVTj8p3jG4d37wgiPOAnRq0mSwcW6m+zqhozT03YIRYX3ExNHVDKTBKGJC+H3RlXqCOtw4LprJG5e7hdSsQhRq7aoTwtDSWQS85+YKBfPYcbFGU/dllnBWV8Pb0q5kEsWMZIAgMuugt7QxL19sD/SSvBbkhCtiZIcARxU+vI53DmixIrAAAktmd7Lhpc0BzhYL99b8oFVskDgoOw8xaLmysUz63XrUjmI9XTfY77rogC2qRnmdOKafK88ggYkomIGG7z0HXQ845VfGxA4DADlh7qFDKJ1H3,iv:qL7gN8PCcCkPJJym+x83r/eE/pM8YeBG4jvEjEZu5uo=,tag:Hr09A2NzRxcnveob47hISA==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T21:20:10Z"
    mac: ENC[AES256_GCM,data:LbenYxzCKrisPoHmth0X6EcGMl55v9SXrwwLOzMBe1uJzT18y1N68I49iu5A/pido+p4oNqGcvhwd1r1lB9WTRSZrJ6NGvoH3J/1kvYun5QmBwpj+HMrK7mzD8Az71+guUmlSY1kzhmjdnVXuQN9OrsQWG0jTAAwFGf6HinkMWM=,iv:xqDprseRGLMIuySSyxw7xrAVlOSpYc95mL+blaZtHCM=,tag:eRwQurtYGf1MEHTUtLuwiQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
