apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: global-secrets
stringData:
    CLUSTER_MAIL_SERVER: ENC[AES256_GCM,data:ep2mpETPrLjHKkf8Le4Jf+dnig==,iv:15RkWZNDYZ+1du7N6QaR1WR3Pi1YQ+e6rop9QaI4gyQ=,tag:0lvLhh4k0it4eKOjDmo5tg==,type:str]
    #ENC[AES256_GCM,data:tmVnrg==,iv:M3xmG7vGy64+0WdeKEHMwFr3JtV8GPkoUaT6Rgh/HdM=,tag:8E24fFOZQNSLxLx+ETMlSA==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:kYfDuZuBqGk9+6lYtvptQ1UZwwM=,iv:L52nPkisiqzKtuR8BwjchwYMN7wsmOePsi0xEk4sxx0=,tag:F0c/R/9Y/Meltdzz4GaJng==,type:str]
    CIFS_USERNAME: ENC[AES256_GCM,data:wyOuP5jhgE8r0g==,iv:XcmvjmJsGhIBrdhkJhlFp0VsdDICZK8VVaSBIQheSD4=,tag:YwyGII07fSRhqlz92bRKzQ==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:z7jqis5x2BcxzhA971Pkfe8P8YCyR2X+HKAnUd7ZchU=,iv:lornH/Bcod0Ev+AcGZhtR8Rm0dPVfxS7HfIMe2GjyTE=,tag:/6KasmpmqAJDVI9Hz8/k+Q==,type:str]
    S3_NAS_USERNAME: ENC[AES256_GCM,data:31diPjE=,iv:mz3rbTXESR8J9HPjy6Dg17RmghtZND42c/7/grEGu8o=,tag:RbR2m59jN6Ar3XIURVuxYw==,type:str]
    S3_NAS_PASSWORD: ENC[AES256_GCM,data:UQJ+q+L2kSaZ7MNT+I+ayCQ3Czr8ix3SfoN3UpxacDU=,iv:oMZw9IRr4Mcf30xDFJoCo1z7//n/FG4ALxipBNezJtI=,tag:6HzG0Uu1ybWMys9NmRo3vw==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSi93Tklrd0grOU5tL3BJ
            NUFSbWFQSHVPM2Mwdk9oS1ZvajBGYmJqMm0wCmxobE9PYWhZZ0h3RmdhVkE4WlBP
            QkkyN2QxUUZEZSs4T1cvR3JsbmUrRG8KLS0tIE9FZW9la2NzRENPdjZsUllWbGo1
            LzdHYXZhSWZnMlh6WVZJR09lZ3ZwWlUKSOJHzlZf0M3kBg5/WV4zWOCo/TCGn/sP
            ccvTWqbkavvlEwJG/TgWx7THIaiT0mgcSF03VoF1g1QsOb2IEfo1yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RG1xeGJraDFiYVloUk5j
            VlNkK0s5NlRpaSs2NEtxM0xSMkEzSmlZNTI0Cm9qSmlJTmZ2elkxUnp2Q0x3bUYv
            c3o1YWZFRFRvVnNvaGg3T3ZSaCs4T3MKLS0tIGlKd3BjbEF0b1Rjbkl1YUtWNk1r
            TE5zVzJzNWl2VkdhKzRFSGVmaGZ1WjAKt28ZWkPxqNj4ZUcBlC9QGgPVQhwd1toH
            y0a/+Ke1i5ckQw0DlnFQzYC8QofP2+uSIZIeYEZfOtTUR4o25WZz3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:45:58Z"
    mac: ENC[AES256_GCM,data:dpVrkVJWPOrymmb7BcC6f6XSVUVZGzQovfNnMko+gWwl+4c9pjlUrD/I1RscE7PiJB13kI0y9khx4uyaBWwDB9ycenEONaJElKNhC2E7IbsJK+3+4r9KAwcLPivWVjhdL1kDM+pr+pDHZTTXvZL0gBsnjNiadeskTann8P3SPyk=,iv:bT2PcfhmplF8J3l66N5phn3TF+fZEGJMVWjn7+8Kk4g=,tag:POQ+M5NnBn30vUP7rHcQSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
