apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: global-secrets
stringData:
  CLUSTER_MAIL_SERVER: ENC[AES256_GCM,data:ep2mpETPrLjHKkf8Le4Jf+dnig==,iv:15RkWZNDYZ+1du7N6QaR1WR3Pi1YQ+e6rop9QaI4gyQ=,tag:0lvLhh4k0it4eKOjDmo5tg==,type:str]
  #ENC[AES256_GCM,data:tmVnrg==,iv:M3xmG7vGy64+0WdeKEHMwFr3JtV8GPkoUaT6Rgh/HdM=,tag:8E24fFOZQNSLxLx+ETMlSA==,type:comment]
  NFS_SERVER: ENC[AES256_GCM,data:kYfDuZuBqGk9+6lYtvptQ1UZwwM=,iv:L52nPkisiqzKtuR8BwjchwYMN7wsmOePsi0xEk4sxx0=,tag:F0c/R/9Y/Meltdzz4GaJng==,type:str]
  CIFS_USERNAME: ENC[AES256_GCM,data:wyOuP5jhgE8r0g==,iv:XcmvjmJsGhIBrdhkJhlFp0VsdDICZK8VVaSBIQheSD4=,tag:YwyGII07fSRhqlz92bRKzQ==,type:str]
  CIFS_PASSWORD: ENC[AES256_GCM,data:z7jqis5x2BcxzhA971Pkfe8P8YCyR2X+HKAnUd7ZchU=,iv:lornH/Bcod0Ev+AcGZhtR8Rm0dPVfxS7HfIMe2GjyTE=,tag:/6KasmpmqAJDVI9Hz8/k+Q==,type:str]
  S3_NAS_USERNAME: ENC[AES256_GCM,data:31diPjE=,iv:mz3rbTXESR8J9HPjy6Dg17RmghtZND42c/7/grEGu8o=,tag:RbR2m59jN6Ar3XIURVuxYw==,type:str]
  S3_NAS_PASSWORD: ENC[AES256_GCM,data:UQJ+q+L2kSaZ7MNT+I+ayCQ3Czr8ix3SfoN3UpxacDU=,iv:oMZw9IRr4Mcf30xDFJoCo1z7//n/FG4ALxipBNezJtI=,tag:6HzG0Uu1ybWMys9NmRo3vw==,type:str]
sops:
  age:
    - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0xFcUt5QmMrMzJJWFNm
        OHpoaEMrcXJpVW52OTJNODQ0YmxLb0c2V3hNCjVBMFRMOGpYcStGK21VelpZejY3
        Qk9tME1CZm1MQ1lVSXJ5ZGFOOXE3cTQKLS0tIDZIWTArSDlXMDY5aUtpUkE4L1NG
        ZHl1Mm14Vk01ZWhmd2l0YW1NSHBJUzAKj1biNhdb0VVq6M1t1P22KN+2s4yN95mk
        n/zByiNuvfNMzkyLWul86DlLPEAlZjwXWzCX+UGTH1wSBA4TaFw6ew==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WE1XVEg1Yi9VdE8xenJZ
        dXM3Y2l0WkxiUUFUdXVMMklZajdlTDc1SWxjCkdaUHR0ZFVPT1Q1L3dTNEpNMXR1
        WTZWMldsMzI2Nkd5eHJmelFoRXFLVjAKLS0tIFFSNzJWN2RlV2xDeU1WeWE0RkJZ
        cVBQanZKSUE0aGltMVdjSWU3VjI5TEUKIM9ivlV3RO/kmVL3EjGhVcMRCf+ITUPC
        Br6hTZNajxIH/3alGc3eClGvt9r5KZi5HJHT6OY3JLCnetIkIYX82g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQjRQd201Njk0SXNSQXlU
        TW9Ia2xLWlo3WVN5STF6bmc3S1EydzNYQUFvCnlHa0tOTld2NVZCM1gzVDRUbDJS
        dmNIRStGa0ZNckZpdUVveHFWa3RRQ0EKLS0tIHI2bE9KMTdRNDVtdjIyTjYzMjln
        NXU4OFVQNTFiSnBzZ2Fhc3pseXJZRHcK1CGBmasVYo6D3nwBjZKqyD2Pe6e+6uGP
        vuFevxni5E/8jChIZU7hmDfSzyLLEM3AEWXsATXlDGTN2oTm3Eep9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T22:45:58Z"
  mac: ENC[AES256_GCM,data:dpVrkVJWPOrymmb7BcC6f6XSVUVZGzQovfNnMko+gWwl+4c9pjlUrD/I1RscE7PiJB13kI0y9khx4uyaBWwDB9ycenEONaJElKNhC2E7IbsJK+3+4r9KAwcLPivWVjhdL1kDM+pr+pDHZTTXvZL0gBsnjNiadeskTann8P3SPyk=,iv:bT2PcfhmplF8J3l66N5phn3TF+fZEGJMVWjn7+8Kk4g=,tag:POQ+M5NnBn30vUP7rHcQSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
