apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:cMzJUlBxJcpXL6lf0LjanA==,iv:GObQ7Y8DaZ+JtYRfNibeAmok0/YrNaXnARTCuL7nBBc=,tag:fMJ2oyUr+btJ7xzdpU+W8A==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:6hw6O7brvmIonvljikqE,iv:m9wFonNuNFGwKq0oQcKnSWGvZNMpv0fV0lgIEqjgFkY=,tag:dG5AQhFAbLRGlIyTuci8SQ==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:H3id6314t3luldZIiCty,iv:w1cryoG+0BOaQS+xZTx+nsjPOZaS6vRollc4YS7RcUU=,tag:s3WDV36yY0m7TIuW9ElNFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15gheadx06yqv700xe3g3ra9x85fn9xqu9chqt6fhh2caevpcgsrqlg6tlx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS1RMM2pCWk1iTlI4c0dz
            S01IZnZLYW02QU5yVVNuaC9HN2Y2TE1hQ2o0CnFac0hnMW5NUkRyTklZWW5Ca3Mz
            S3NSdkRjdWJpeHZ0TkJCK3N1eTJpTkUKLS0tIDhBWWZBaDZKdVczdEpSOFpTZCtN
            ZFF4QXpBc3RzUEwyN2taY3liNldudmsKoruh/ASCg5B52eBN+0WfNIookD7ew0Ce
            a6tNzjzi++Xq96v54aIJf/2eQyMP5kKkqoXE//9hhuhw+hUU9Ug+pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN2hmeVh3UzR5MU10eU1J
            WURPMUpYeWlFbkJDWXZSRWFqcUdhYTdvdHlBCnBuZ05RclFyUjAzN1JhbktrQmxU
            WWd0dU1aUktiV09pQzdsWXlUcmlxNzgKLS0tIGdSZjA1UXBheGgvTFUvdkVBakZS
            d1BRaFh5WWJjU3NGZ1FiUm4rUUhFeXcK8O9wzppPlnnUhpzn/rRQ3sO7TEOsWQxJ
            6bR29gLaaS7pJI0Fl17BrMVysQe1rjjhZvYa57NKuBu+v/P4NEjWIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T17:14:50Z"
    mac: ENC[AES256_GCM,data:7JRmMd5orlJf+2eJ1kOg9/djb8Y+ln23j+TRLvh1P6tz3LFauWnhrSnHFq5JMFNXOmCipRLuMAtbE/76AuMyDZPvuwfRdduM9jpIr2EJRQ23OSc5JgXapUpW+a8AXa8bDJTZv5WX4TNMLNdFVl/ofppprI3UcEcqDbGQ5vXB6f0=,iv:7teaX6Kk3hKvtGG5IoBbBABxzh9iw+UD44nSmXCZwSs=,tag:sWShqk+5ZZIBXy44JVExmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
