apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    OAUTH_ISSUER: ENC[AES256_GCM,data:WmNEhtRugKCEclFiGb/glJeH9RlWCPlXLNFHWxF/80JqnkLwp/hRU+RT+aWPvnWPazI3NRwLeOL8plyEvA==,iv:GapFJO4Qpe4Rb+teyMbhkH5FuWbXkzeL2ZzQ0IwU6YU=,tag:vGjdrnyN5kz/43mWICPMlA==,type:str]
    OAUTH_ISSUER_CLIENT_SECRET: ENC[AES256_GCM,data:Afdbe/rOxaYwWzFCLUUZNBO2sKIFfyyhqh5qKi2i+Ws=,iv:MeVVcDBS3zVidLVUcpAFjLTHqh8PWNW5c7sDNwdMx2I=,tag:MtMjEzr281NudZ2N69YGaA==,type:str]
    #ENC[AES256_GCM,data:79HcidzPBBN7AqgaQucu/Q==,iv:o6rh8nZeQClCUZ7d4VNKKjseyTxFDcJMhTh4ZPUk/xc=,tag:1Y/6Cz7kvdFcNYO4+VuMrw==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:IfTlShE3sDMgIfcV74bd,iv:B4oEWys7PO620ql/VU6uFTdvgBp2v6pRCEA4D3C+p8U=,tag:S9qPOi08Y3JJz5826gX5kQ==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:3rIqQEFadGJD3OxJhZFw,iv:/6b9bVDoNsFliwhlnsIDoS3tGbq5JatWP/5fT/22v/U=,tag:lD7JJbGmCRYYUJpLuSQaRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15gheadx06yqv700xe3g3ra9x85fn9xqu9chqt6fhh2caevpcgsrqlg6tlx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZmhWdXpRVy8xdUN1OFh4
            SXN5WGxyRElQM1U5V0Z5aWpJelRaL1AxdGg0CmxTT2c0Mms1bWJtdlZIVUwxMnVw
            Q3grU2p6aXh2MHVydVh5bHBKeSs0WDAKLS0tIHg5THNIQ2JYbEQ0N1FYK0lpWTll
            WGk1ekpFK09yaXB0Zi9JeDJPdUpyN0kKdDCri9ovilPGgTUxOlzqnHKCWsI9ZPDK
            VXWrobgk5h3nDUrLlVfpXfN/uDHMWsJtfvOxdcXanC1/bpGZHv0z+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYejI2cFFnYjR2Z2piVGVK
            ekRYb0xXL1ZQalBjNlJQRFZ1L3M3WHNFU1J3CndLTHZMWHFCdnErNnRjbnlBOUpG
            SkU2MG1uZFFMTnpsTFVoTlFMVGRPWVkKLS0tIFA5d3Z3bzdTamV1OHMwdW9HMXpN
            RWFIbDFxWmFQejIrb3hvaXBLdlg0cnMKSqXrMUvrUD0TyE+MKoUoD27h4t21eLmP
            9TFPVa6Nb8YuyimDJqMu5qqE0N57j5vNjvKd6c7sLQRj9/0gMVpOoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T19:49:57Z"
    mac: ENC[AES256_GCM,data:+MrRePzc3b7G22IMydU00VRLnEpgZeMlFB09KG879XdGpzilGA/FgvbY90HT49zKH/u2fmaCSDPL7FqB+dsZPjGN7soJSuYCAkhVwDUwSFY9PUmSVC9R7QA3scjXZtLaAFIEJlpmuIVVV4fK5q2nKRbNEwdEsTwyFu1aWHpe7PQ=,iv:BlAo44xUGw0BmMFPDbyfMjiG0C9mQM2c+qVn0o5muGs=,tag:6m49k3l1r9ZYBdyC8RLqCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
