apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:1LQZHQxg4datDR3eRN25iw==,iv:DJOodfzqLZ/1SgPaFRYDJlnSwNtWMqWP/hlitgW4snc=,tag:qCbg3l2PxlJM0ccXWGV6oQ==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:UbTp6v39bb6jT3MwoQXZ,iv:PAymzNTK9f4sI5xIsrS3ENlZ/NFxIvdqr5xvbdcwh4E=,tag:BnxyCNlxk47qXDuPxhJmVw==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:MsxuKsvw4cJ58DvSoHkw,iv:tRrJDRRaix8b+FV9+bytvDCXOfe6qQIIs52Atf/TmVs=,tag:UX6KyGTRjoKKzmX4FrBwww==,type:str]
    #ENC[AES256_GCM,data:u90v6Hnf1DQ+b6p0RL1yETp/qw==,iv:kvPLNk2x5YoGYbkbegBk9xXqyUksB97Nv5Bm6zjvRto=,tag:qkpQuN4wOI9Vv6r9VcBFyA==,type:comment]
    OAUTH_ISSUER: ENC[AES256_GCM,data:5UkSZku5G86NvE2m+hNmw6WiQW8sMZ08ATI3LcxtrPdOJWocqe2SGfkhuKvKKBUSI09+XqnHt8NBNAx77Q==,iv:jg/J/b2Hj5amYYZoRzChXy697wqsYWJQazU3TLgWDAI=,tag:4JDYVUO6qW14Lpgcb4+C9g==,type:str]
    OAUTH_ISSUER_CLIENT_SECRET: ENC[AES256_GCM,data:V+7NmJwlNBISWQjAG1bDHbvinU015JHU0CVF5gcHdZE=,iv:Q+spDFNxveG3Zlq2yFvr5PRKHuRa/5Td3D+6Uak8YYU=,tag:6g5zjUA3iVQJOu86RUw5+Q==,type:str]
    #ENC[AES256_GCM,data:HyQiEw==,iv:51j7onRupy4wIr9tz/svJrC8ahvwOVcX5i1eZ3UsyZg=,tag:1qcGS0fpwdLkwHr0OvwzVQ==,type:comment]
    CIFS_USERNAME: ENC[AES256_GCM,data:pRMDdJjiUK6uHA==,iv:uXY8RElEURxsX10A8ZwD//r/CYcrlMIolPTm8mKULvw=,tag:bfk0eVdyoaKY0ujG3BSzFA==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:Jrh4kdK3Bqor0EjSiG+VsMwkqkZK4NfXSwVVuIhV0Wo=,iv:tv9DTfmxhiyVsu4uB8tz6hrbs5MY5ATqbPyZcMDC4V0=,tag:SFB7M5pkgBG3n1cLDeK3iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15gheadx06yqv700xe3g3ra9x85fn9xqu9chqt6fhh2caevpcgsrqlg6tlx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMWxIYlRYejBucXFqQ0pC
            clNUb0xTc2tVWnQyMWROOE5xeThKdkx5SWhVCkkwbXRlSThtcEM5SlhmRXNtMmtz
            S2pzdzJhc3R6VTVQcDhHMkZTT0xzR2sKLS0tIE13bldjcmN1b1VGRUNOOGFjOFRY
            eVRCckRSTUUxZVduM01IV2xqZ1p5c00KwG6O0+xXRwlPid5Qf2EWuniokdTHV+1l
            Fj/PRWgkKevrjcmFt5fH7D0rjpYtlB7UHMaqcqQTjbei1IgZshlKjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YjIvVmtJYUlIYjloVmNB
            SEFBeDY2NytIYkNMYWFtUUdlQVNCNWU4OFFZCjc4UEpvZGZLcVhsZkVkNE1WMVBh
            VHNmTDBGSHFWWFFtZCtnUnFsZHdWUzgKLS0tIGEvWW9ZemdSWVltOEYrZ1AzOHll
            RkI5YjFYbkdSNlhnZVNQUXR2Zk05Nm8KuZ2GyzuhytcRxq4lMtWK+kYaLadHSD1m
            Tl+7sb6dwG7mpUY1x2vZGrpyjWr9j7q0c1hteVxvyueNq5HO6IRWtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T23:17:37Z"
    mac: ENC[AES256_GCM,data:TXWol5LuQfjgwudML3vjDfAdM6PLK3ZHkHCe/nSt3cMN2g9V0Q9D6JHPG0qUJ9lvFRTZIb+e1PqALvTixMPf2iqjjG6Tgg/Fx6IdDHN76kcT49fGwTDoUymAsx/vE5wEJJ08i79C6cvqmUCmFhRoQclao5jLkwywdlIE+6LlDx8=,iv:Q1C3KNUPCf8Lf2KQv38Gm0N8+o40luQ10SKYecTXNoE=,tag:bpyESV8wTWcjkQJcJZe43g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
