apiVersion: v1
kind: Secret
metadata:
    name: tt-rss-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    tt-rss.yaml: ENC[AES256_GCM,data:IOnoIPyyBkHCS6TgFDtTjq4O1RbUi7QaPFgwjHsjwHoVocOJKZV5ChhHha79xcjLaTKMJCWNw5t3cqyCknRpBtWUVs+25hxNLadynnuEiphBR6Z3uOXdZk7HF5UA33JtAAbNfXidzIO1DUufe8YjGhFGokHiI+k1xdQBKvwJL4YPqgIcYgd5BDc62/11PijJ3hhZJa3OG/UdwlAxJl3AUv+ENGqXk0H/Zd6OaalzriTaUcte/X7wKauSN5+5EP/7w18nmVtKZ2stpivAodNDHbV+8lO92vUpNEsE39/NnZSBe22iF7IbNooCL6MjopaObmFlmqY98X/8kuvrqKhegbp8VQuR2FGfnWgRpN7Flb7BFDunT4fwT/ylmihoYao1BqaDVnMQDKCYpEoWSjCx9nYtnNhom2wVkIq/t4phhLqlHI9uy1s0S8qYpq3Z4oPRO3pNkeziyZCzvxbZSdYxonroB0PCk2G5ro3ym6iKoEoC6B9AgEZIT7utvLiJWUfLC739WyEniYNRgno=,iv:nWlg9bLZEw+VxicCkZqnwkUjkANKRgHNSBKemxnRz0g=,tag:vPPNgDEYSW5jlZdcR62MxQ==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T13:40:31Z"
    mac: ENC[AES256_GCM,data:9S5QRfFMRGN84mg4yyOdK+lNqu/xHpTcq3R77c/vz2/lxO4B6Tcqb5nCEjhi2JmXQoFU4tIf8ECRt3ecXvY7aybHP5/sZd9Dsj/0NOAd8ZTzesaxbJSeSWexcPzecrVrzINq7y1L2x7EVbzsPWOJEbv0nymdYIrG18DVSYRwsUs=,iv:P3QyipZVOiytxKfWCfAuKpt5nNtfaYXIlZUh+OG7424=,tag:Y8rs5Xark6Tt0o9KIfF0SQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
