---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Cluster dependent
  CLUSTER_NAME: prod
  CLUSTER_EXTERNAL_SUBNET_PREFIX: "192.168.5"
  CLUSTER_LB_RANGE: "192.168.5.128-192.168.5.192"

  # Common
  CLUSTER_DOMAIN_CERT: cluster-domain-cert
  S3_NAS_URL: http://192.168.2.10:9000
  S3_NAS_POSTGRES_BUCKET: postgres-backups
