apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:1LQZHQxg4datDR3eRN25iw==,iv:DJOodfzqLZ/1SgPaFRYDJlnSwNtWMqWP/hlitgW4snc=,tag:qCbg3l2PxlJM0ccXWGV6oQ==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:03vipctrJlNiJQtF5rn7sw==,iv:xtcSOXx/NPHXrsA5WDuTWd3MBAmETB1BBo6YHROy2TI=,tag:kMy1LAAiBbkpGOPhH2blzA==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:ppsylZIzNBjcxpWgtUziNw==,iv:1QPB1pOa2YqaACLWGwXOC6PWXGOXx6xR1XuM2xhGnis=,tag:Pw9doroOVm6qyou4bT+CBA==,type:str]
    #ENC[AES256_GCM,data:u90v6Hnf1DQ+b6p0RL1yETp/qw==,iv:kvPLNk2x5YoGYbkbegBk9xXqyUksB97Nv5Bm6zjvRto=,tag:qkpQuN4wOI9Vv6r9VcBFyA==,type:comment]
    OAUTH_ISSUER: ENC[AES256_GCM,data:dlszVEfMQqcSsQg7hLRsUrzVLOpuF2pBFDgbj1aC0h0q3/aRcJI44l54lsol6T6689J9yBwdnZTMBQ8n,iv:0UsNC40AQh/MH0+V3j95uJUBudyasPeNQ7ksHg34ZeI=,tag:5zCx4YTTL6b5K4PDt+oHDw==,type:str]
    OAUTH_ISSUER_CLIENT_SECRET: ENC[AES256_GCM,data:V+7NmJwlNBISWQjAG1bDHbvinU015JHU0CVF5gcHdZE=,iv:Q+spDFNxveG3Zlq2yFvr5PRKHuRa/5Td3D+6Uak8YYU=,tag:6g5zjUA3iVQJOu86RUw5+Q==,type:str]
    #ENC[AES256_GCM,data:HyQiEw==,iv:51j7onRupy4wIr9tz/svJrC8ahvwOVcX5i1eZ3UsyZg=,tag:1qcGS0fpwdLkwHr0OvwzVQ==,type:comment]
    CIFS_USERNAME: ENC[AES256_GCM,data:pRMDdJjiUK6uHA==,iv:uXY8RElEURxsX10A8ZwD//r/CYcrlMIolPTm8mKULvw=,tag:bfk0eVdyoaKY0ujG3BSzFA==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:Jrh4kdK3Bqor0EjSiG+VsMwkqkZK4NfXSwVVuIhV0Wo=,iv:tv9DTfmxhiyVsu4uB8tz6hrbs5MY5ATqbPyZcMDC4V0=,tag:SFB7M5pkgBG3n1cLDeK3iA==,type:str]
    S3_NAS_USERNAME: ENC[AES256_GCM,data:2IBrppQ=,iv:XiuS6IW98iqPLaPBgObJ5VVD7ZpnixIQ6NrnODFUVU8=,tag:1JgHt/Glu+/Tb9pOzN1CJA==,type:str]
    S3_NAS_PASSWORD: ENC[AES256_GCM,data:ANjcYNAKBnUqMsbOanrj2FptSaITwwNbgiRiyuZHUj0=,iv:hpUXeW30ym8WALvA73KVcoM69iZqvHiJfGGvlYfyifY=,tag:naDIwKjDbizDWl+1674wDA==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSi93Tklrd0grOU5tL3BJ
            NUFSbWFQSHVPM2Mwdk9oS1ZvajBGYmJqMm0wCmxobE9PYWhZZ0h3RmdhVkE4WlBP
            QkkyN2QxUUZEZSs4T1cvR3JsbmUrRG8KLS0tIE9FZW9la2NzRENPdjZsUllWbGo1
            LzdHYXZhSWZnMlh6WVZJR09lZ3ZwWlUKSOJHzlZf0M3kBg5/WV4zWOCo/TCGn/sP
            ccvTWqbkavvlEwJG/TgWx7THIaiT0mgcSF03VoF1g1QsOb2IEfo1yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RG1xeGJraDFiYVloUk5j
            VlNkK0s5NlRpaSs2NEtxM0xSMkEzSmlZNTI0Cm9qSmlJTmZ2elkxUnp2Q0x3bUYv
            c3o1YWZFRFRvVnNvaGg3T3ZSaCs4T3MKLS0tIGlKd3BjbEF0b1Rjbkl1YUtWNk1r
            TE5zVzJzNWl2VkdhKzRFSGVmaGZ1WjAKt28ZWkPxqNj4ZUcBlC9QGgPVQhwd1toH
            y0a/+Ke1i5ckQw0DlnFQzYC8QofP2+uSIZIeYEZfOtTUR4o25WZz3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T22:32:01Z"
    mac: ENC[AES256_GCM,data:kk5qh9CAAztOUn25zaKEixsJ2egzHvO7quNIIwHo708I3/iapDCFO1MYJ/12GM71ta+44IfS+iOBHUEjgmCYa2kujC3CeXGnYdBYqYKSvaNflwm9eZYKuC9GwFv4Hz1O1F4awqLkDc+B1lZGM8PbYO4DdNOFdcm+0jac+RTV1+E=,iv:9j0p1Nt9GCGvWdPgb7W1qtnY7E5l+YyxrwCRQpNrO+w=,tag:7vLbdDRaKsrF1SoXMP00Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
