apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:1LQZHQxg4datDR3eRN25iw==,iv:DJOodfzqLZ/1SgPaFRYDJlnSwNtWMqWP/hlitgW4snc=,tag:qCbg3l2PxlJM0ccXWGV6oQ==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:03vipctrJlNiJQtF5rn7sw==,iv:xtcSOXx/NPHXrsA5WDuTWd3MBAmETB1BBo6YHROy2TI=,tag:kMy1LAAiBbkpGOPhH2blzA==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:ppsylZIzNBjcxpWgtUziNw==,iv:1QPB1pOa2YqaACLWGwXOC6PWXGOXx6xR1XuM2xhGnis=,tag:Pw9doroOVm6qyou4bT+CBA==,type:str]
    #ENC[AES256_GCM,data:u90v6Hnf1DQ+b6p0RL1yETp/qw==,iv:kvPLNk2x5YoGYbkbegBk9xXqyUksB97Nv5Bm6zjvRto=,tag:qkpQuN4wOI9Vv6r9VcBFyA==,type:comment]
    OAUTH_ISSUER: ENC[AES256_GCM,data:5UkSZku5G86NvE2m+hNmw6WiQW8sMZ08ATI3LcxtrPdOJWocqe2SGfkhuKvKKBUSI09+XqnHt8NBNAx77Q==,iv:jg/J/b2Hj5amYYZoRzChXy697wqsYWJQazU3TLgWDAI=,tag:4JDYVUO6qW14Lpgcb4+C9g==,type:str]
    OAUTH_ISSUER_CLIENT_SECRET: ENC[AES256_GCM,data:V+7NmJwlNBISWQjAG1bDHbvinU015JHU0CVF5gcHdZE=,iv:Q+spDFNxveG3Zlq2yFvr5PRKHuRa/5Td3D+6Uak8YYU=,tag:6g5zjUA3iVQJOu86RUw5+Q==,type:str]
    #ENC[AES256_GCM,data:HyQiEw==,iv:51j7onRupy4wIr9tz/svJrC8ahvwOVcX5i1eZ3UsyZg=,tag:1qcGS0fpwdLkwHr0OvwzVQ==,type:comment]
    CIFS_USERNAME: ENC[AES256_GCM,data:pRMDdJjiUK6uHA==,iv:uXY8RElEURxsX10A8ZwD//r/CYcrlMIolPTm8mKULvw=,tag:bfk0eVdyoaKY0ujG3BSzFA==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:Jrh4kdK3Bqor0EjSiG+VsMwkqkZK4NfXSwVVuIhV0Wo=,iv:tv9DTfmxhiyVsu4uB8tz6hrbs5MY5ATqbPyZcMDC4V0=,tag:SFB7M5pkgBG3n1cLDeK3iA==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQVoxOXc1WGIxVnVyY0VS
            TXNvK0liQUY3a3RSUjR5K0lsWExEVENubldFCjByQVRWMlcrM1ZGd0EvOHRjS0hw
            ajRpeFZDVHNJS3hvdkY5NXk1SkRRR0EKLS0tIFk0dHBkcUN4STQxZlRnNGhhZmdZ
            RklZd2tWdkc2VFZ0R24wQUo5Mzk4azgKgNHCjtAY7cDn/fIl2Y2fKCVVPvdaTG6J
            K2kVth4t5/n12Ua4N/a+5/b2qUrgAGlnUeYAhju1WvB5VJRD6ixZEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbG9oOG5XRUZTblJEemcz
            bWkrLytpckU3L0FMOElWUG0wQWVKOTZ6akRJCjFIR3VPNHhTNlFvSWJOM3JsRTln
            UVR0TUxrOUNWUmlNVDRVTE5yVDdSNzgKLS0tIFZRRCtIUUNpcElQYUdScHcyM3gr
            V3BKaW9CMzdSc2MyM1hmZ2VwS3FLOU0KIkYE4myGe5PjN5Cf7rhpTTAWRbidWU+4
            wUYqYeoBbEVPwUQL6tMAT6eqFFiMdGNSt4GwIF/bC4dI5DddRNbbqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:02:01Z"
    mac: ENC[AES256_GCM,data:Z2cGgvtFaHFuMHWKJksNTDyvhcvCGCK26XcXV5mQjg7AXPxFs0TfBrvxNdhwgmxCuHri2iP0z9HPvRb82WtsjuqFELh6Lz1uCIYqRRACTh9Z8ke7/DoDgp9LEVenjj7nF7sFzrTzxC9LADz8Bh42dMtWXKIVRVoy9IltRM2vDY4=,iv:vkMS41QQpCUMSs3Z9ZjQDZdMARQxJADYDpzfVFwxhKA=,tag:ZP1m/YL0c/iDhbGB93JKDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
