apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:y/HIqT/9fE22sRId6+Gu0gE=,iv:UaepdvGxyRw9zh7H13CpOXvfPV0gtS3NoYQXL1x5S3E=,tag:7HeI/XE93XSbl7c4G115JA==,type:comment]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:03vipctrJlNiJQtF5rn7sw==,iv:xtcSOXx/NPHXrsA5WDuTWd3MBAmETB1BBo6YHROy2TI=,tag:kMy1LAAiBbkpGOPhH2blzA==,type:str]
    CLUSTER_SHORT_DOMAIN: ENC[AES256_GCM,data:ppsylZIzNBjcxpWgtUziNw==,iv:1QPB1pOa2YqaACLWGwXOC6PWXGOXx6xR1XuM2xhGnis=,tag:Pw9doroOVm6qyou4bT+CBA==,type:str]
    #ENC[AES256_GCM,data:jfpctyEH+EmgxQvUThVVFGPlL93DeaO8Pw==,iv:DdeIyiIs7hFnbdH5Tx38FF3gwKDzTxQay1iUFgk8eG8=,tag:L1YMIEWo2lSPnoO5BHX0/g==,type:comment]
    S3_NAS_POSTGRES_BUCKET: ENC[AES256_GCM,data:l8pw3XK0tw79vEtnl62bPu0+/msr,iv:7tlzfDZl20K257k0jqhHvf8O93+9PJz7PG90SOpS2MQ=,tag:xxW3i616utF4weROwBwRfw==,type:str]
    #ENC[AES256_GCM,data:a7QtW6H9UTDMlN3bvxyPsTRpg+c=,iv:xiOg8uTmVYGYj18m8UtDcqHg7sxAIok8yft+cMywQek=,tag:dpPo5YiiKFIlMYLFbM0w8w==,type:comment]
    OAUTH_ISSUER: ENC[AES256_GCM,data:jei4VYSSrBJN045ze/kLFf8dmJuJXx5NFkXbHb9xqetA3fty/61dyPvZJvGwlYD7B5OMj0w0iixMSG7I,iv:DmVGKGl35sgXNTSLnGWpWEctXT5ce1Sro49joIX0HOA=,tag:Kh37uZQekCErf2W7YbHB3A==,type:str]
    OAUTH_ISSUER_CLIENT_SECRET: ENC[AES256_GCM,data:V+7NmJwlNBISWQjAG1bDHbvinU015JHU0CVF5gcHdZE=,iv:Q+spDFNxveG3Zlq2yFvr5PRKHuRa/5Td3D+6Uak8YYU=,tag:6g5zjUA3iVQJOu86RUw5+Q==,type:str]
    #ENC[AES256_GCM,data:ZHC2BJ1J3srNVyMjp/HMM42dIg==,iv:EqMgFoufboCf7SAw/nsV0SyDwtRDR3ewnOTM3IWSJ6g=,tag:Idu/eElUP58dem2MyeuTLQ==,type:comment]
    FLUX_SLACK_URL: ENC[AES256_GCM,data:kE3OtLmTcN1SvoQEGGaK7+UqqVqsLuUTDJXGkqfRigcIyz7hqZQAvGejTZL/ebJbakEMIkspcXy0DYLILiog4L1GBRD2yo27NdrgYiEwHR5G,iv:nB2/FFM1HxspnDnb7kJyFLf9JadbIayDG5JLLWWhiVk=,tag:iRkGBRxMDLr2kGWPae0Nqw==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSi93Tklrd0grOU5tL3BJ
            NUFSbWFQSHVPM2Mwdk9oS1ZvajBGYmJqMm0wCmxobE9PYWhZZ0h3RmdhVkE4WlBP
            QkkyN2QxUUZEZSs4T1cvR3JsbmUrRG8KLS0tIE9FZW9la2NzRENPdjZsUllWbGo1
            LzdHYXZhSWZnMlh6WVZJR09lZ3ZwWlUKSOJHzlZf0M3kBg5/WV4zWOCo/TCGn/sP
            ccvTWqbkavvlEwJG/TgWx7THIaiT0mgcSF03VoF1g1QsOb2IEfo1yw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RG1xeGJraDFiYVloUk5j
            VlNkK0s5NlRpaSs2NEtxM0xSMkEzSmlZNTI0Cm9qSmlJTmZ2elkxUnp2Q0x3bUYv
            c3o1YWZFRFRvVnNvaGg3T3ZSaCs4T3MKLS0tIGlKd3BjbEF0b1Rjbkl1YUtWNk1r
            TE5zVzJzNWl2VkdhKzRFSGVmaGZ1WjAKt28ZWkPxqNj4ZUcBlC9QGgPVQhwd1toH
            y0a/+Ke1i5ckQw0DlnFQzYC8QofP2+uSIZIeYEZfOtTUR4o25WZz3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T11:09:53Z"
    mac: ENC[AES256_GCM,data:sVOCeF6rqDY5zSOC7HcMgsUKPXZ98ZhA1HzJd4Rb+M5z89iVVT0SLbcHlzLl/NeKETiYhI1+hK9zKzDrbO10Si2mYW68JYhqlQVnR+JABzOzpDMs4ZOi752SEqH3x8ug0pUfeVm0AxdphpH1GHmZe9JXLZGfwRVsw0bn59k8S6I=,iv:RzKuTn7dtJ01IcYKitRkj3oNVi0jBqKeEwMeTUT0LGs=,tag:kJ0u1Ilf/zS5PGxt3tXo6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
