apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:0K49J27twMb2IRqtNl/qXdscYkuQH8hiPrB3JWPRReLPmiU=,iv:7H0zzDMgXIDoQE6K4YTzInJ/qjGySetEhNCDRcjDnAs=,tag:ZxnHSH3klxWo1+JEagbmnw==,type:comment]
  #ENC[AES256_GCM,data:7iW1eu6LXnQHtHc25g3BcNOdmilYQt3w3CPIsh3UbtRc3tls9prF4GvPSVpTdsjBABpsmOZIK+T0L9n5zakH17lSZnwMqOAAIBXT,iv:/icBcQsMzDE2Bi0nNDVFTGSGlltadqeqQJ3bTjQ07S8=,tag:If1ugX3AfsD6OmXpleeYdQ==,type:comment]
  age.agekey: ENC[AES256_GCM,data:ct8C/EULktCRKhR2H6o4hh1B8gUNSgveu7Wk0dqMdZVasGPL/315gcKhZwT+AhwuaC4j/9rfy8GGata6EhtXF3j/b0ytlWAKRVU=,iv:TZ+WckMZCoLEgXdOTpzM7AJN1MPMu/k6gjRglFXcacg=,tag:QXL+t8THMFx4JE3lzACVTQ==,type:str]
sops:
  age:
    - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaHhFZWpkRVBuK1NYSWYz
        SEs2TUdyUXgrcEtIYXA0bjhWVUJIZHVCWUhjClJmMHNDV2ViaWNRcTl1alFaTENy
        b0pFSHZBWkdTVy9YeUJHQ1hEMUJ2MmMKLS0tIHd6S21meXY0dmMrMmRrNXJnb0hD
        a1BtZ1I1QzQxZWR4dXJ3L3M1cGFsMjQKK14qE2+BQ+89LshbvNEWVOmvVJFxdoWY
        or7pdlGz8nMjq70Dp+LAluyYvh+Rpnru1ST4caOdz6mHULcgmtzx4g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycnh5Q0wwN1B0UjhRVFk1
        ZlFYRnE0QzZjWkdjWU1NUzJDSHVVbmdKaFVvCmhWMytCd0VnQnBJN3ZvN1RiUlcw
        b3hIVEJEVHVmUFlIR1hXOUxFZ3BFQlEKLS0tIEdGZ1JEWHlaQkF2d3lBam1QVUlK
        UlpSTTg3NWVKS1B5QlRpWTdqZnpjL0EK+3TBNIHYWWgFzt1+aNUr8Ruwn5dMBxxY
        XbLLqHDZumP500+lSjeu3IoIKRQyOF9TQpfyLZRhdxT39/gbxQdVWQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCai9UeGtkb3NjQVJubklT
        TGVScDNPRW9SVDRGdGRPMGhVek12dGlsWkJzCktIMWxOeTJYc2lEOE1Bd0hKZzRx
        d09lVDE0UkthOEZ0WnhoNTZ3cExpcEEKLS0tIHU4THlmRnNXS3FqajdCMEo5OFZk
        bkhKYTMyR1pBWjZ4ZWFKZllkVGlib0UKcyYGTRZ1QooyCvxpSCGCN3hvOhxuAFRx
        GetBH2dBF45OurVfHnQCaYY1QFkwEXvj7K7tn7y4rgZF+/eOUAslDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T23:47:35Z"
  mac: ENC[AES256_GCM,data:8sKbYix1KH2u/HZVMOCKtsqV0zuuCU1DuF1uf9TKHSrYfUR5OdKeiCcwqJyY025sZ+wftwtzVHz7cpt5NN8gqqdJjyYuu4Iwojs/dHnAx1MlzPRxEhJ4Qc9cLK+fsEHkLZ3D1NM3SK/nUFU52t8+7bFWyiAgMgZDj51ptxJY+6I=,iv:3SvVkilg47oySyJ/z0IkObaUM7KH/h73YgOUBaAKALI=,tag:lyUdwwIPzKh6llXjqBw4Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
