apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:0K49J27twMb2IRqtNl/qXdscYkuQH8hiPrB3JWPRReLPmiU=,iv:7H0zzDMgXIDoQE6K4YTzInJ/qjGySetEhNCDRcjDnAs=,tag:ZxnHSH3klxWo1+JEagbmnw==,type:comment]
  #ENC[AES256_GCM,data:7iW1eu6LXnQHtHc25g3BcNOdmilYQt3w3CPIsh3UbtRc3tls9prF4GvPSVpTdsjBABpsmOZIK+T0L9n5zakH17lSZnwMqOAAIBXT,iv:/icBcQsMzDE2Bi0nNDVFTGSGlltadqeqQJ3bTjQ07S8=,tag:If1ugX3AfsD6OmXpleeYdQ==,type:comment]
  age.agekey: ENC[AES256_GCM,data:ct8C/EULktCRKhR2H6o4hh1B8gUNSgveu7Wk0dqMdZVasGPL/315gcKhZwT+AhwuaC4j/9rfy8GGata6EhtXF3j/b0ytlWAKRVU=,iv:TZ+WckMZCoLEgXdOTpzM7AJN1MPMu/k6gjRglFXcacg=,tag:QXL+t8THMFx4JE3lzACVTQ==,type:str]
sops:
  age:
    - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QkFiZXFHOXAxa21mcDRL
        aHRpdUJqN2lTVW9EOTdweDd1RnJxMmdMZGpVCnJQVWwvTXpnaFhJT3pEVURSUnRF
        MEJFNzRoRXQ5RzRDamxlOUdYZ1JYZUEKLS0tIDBVeFBIUkw2T3NlemlVRUJoWDJ1
        bFlVTHVOMnJ0ZlRsTTF3OU1tNTFZQjAKbmI2ElOP3Sy71bSGxEsT2lCB0xH/pkQW
        /nsZC9duNuCa6ow7D9wcv3ndNrtzM+TCQsmfv8XaR0VYbUXoAmYjiQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUGpXc1JIYkl3cldvL3Fy
        c3QycTBnbUs0WlhpeU0zdjVTZ041d2d0Z1dJCkx5cXVmR0EwNXRONWlxRGp0L290
        bXYzNWpZZFdIN0YrT1VETXJwaGJsYVkKLS0tIHBsYWF0cDdWbjBQOUd4RUVLYW5s
        YVNjNnA4WnBSZTRCdXdEenVzYkIvUkEKpTriFlYFydUGRmg7oRPZBL1IMZSuuaFb
        8R0Zm9ePfhDRvWi/XVHJpYhd0hCVaNy+FfG23sNfoY52TFvLCI4HxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T23:47:35Z"
  mac: ENC[AES256_GCM,data:8sKbYix1KH2u/HZVMOCKtsqV0zuuCU1DuF1uf9TKHSrYfUR5OdKeiCcwqJyY025sZ+wftwtzVHz7cpt5NN8gqqdJjyYuu4Iwojs/dHnAx1MlzPRxEhJ4Qc9cLK+fsEHkLZ3D1NM3SK/nUFU52t8+7bFWyiAgMgZDj51ptxJY+6I=,iv:3SvVkilg47oySyJ/z0IkObaUM7KH/h73YgOUBaAKALI=,tag:lyUdwwIPzKh6llXjqBw4Xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
