apiVersion: v1
kind: Secret
metadata:
    name: github
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:WfLiTCZ3JByOyaU9198ncLKxo2O3hxo+4A==,iv:jiDkxs7M5hb68WZmay9BBM4gvg0yujMMsrKLxgoqgy4=,tag:n0jejIFHzrstP6CcIa2cMw==,type:comment]
    token: ENC[AES256_GCM,data:hgrbEExu6XwC5C8HRUuf8xnRjgWkIMOiOHcDT6QsSg+mo4ABEy9aQw==,iv:b2rDmkO3ZJvNaMZhFoz8ErEbFCoW6QPwjFEXSCMKwco=,tag:tSfW+kFAqlfv1FRLXfGssg==,type:str]
sops:
    age:
        - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMzlUdGJDQXkxS0kySFpv
            b1Y0K1dSbUVsSHlmSFlyanU4UTA3NFdDUms0CnVBWGxrMWV1VHV1SUt0YjF1SVJu
            OUNNS2YvN29icHQ2dkh6aU5jaEtkOFEKLS0tIENEYURCZ0VLY2tKWm05cU4vOFpi
            UlQxdGczUjlNNXRBRkx4L3lhcitwQ2MKzhCWNEi0snXobgrExIadMOh8H/5MGhiN
            lb/kj5ixhGClFeWMx35iVRqG1Ao7l2SgnQgmBRMDg39W0ZOs0BLGVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pkvndamg24cre2mnnqax9zuvg87686psxfws699669n57we3uqwqvc8705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc1hTTlVJR1F3aXIzMkZV
            elVaVkJNTU9wOWYwQXhpSWlUQ2dKbE9KZGpBCjJJUk5oT1RSUDcvNFdlM2g5L2NH
            V202UGlrdVNIbGR1Sy9CWWRGZEIrVkkKLS0tIEo2bGxjZithc1JadGVzM3RyamFP
            OHRRLzBHangwK1VNR1d4ZFM3c245WEUKomIU1yL9+6RrXmFdE78qrsdfdqDbYR5g
            58jNchKXn56O+FW0Bi0wSlyKJtV5rw2I8FP14Z/iGNE82Vu27yGW8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW90cUpSbmRxekdvK1hn
            cytxNFVuYWptSWpNNW1DSW5SYi9abFAyV3pNCjhySVZFUC9ndm9mVlpFenM5RW5l
            cnp0anBnb0hLdWYrL2p5S1h6cjU0L1EKLS0tIEdhY1ZtM3ppUndlNUI0bytDZ2g1
            cktaclllbmVyak4rWllZUGdwTzdDK28KuaNiMbYjyej9syP47p8jBlbXbH+b9JH3
            MCjPPnB6EPE+BKZ2nmNKdyLeYEeEBXubEirKyCiqkxz4CQZHPZr1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T11:14:06Z"
    mac: ENC[AES256_GCM,data:AeaOTmmDATgDk0Cz6BMSA90jEFgMQ73CTAeDCHM7TCFTpilKjCQdYp6Kwgn01XIUGS9+Kzoc+t2UxOa1IBI1ZBIOUevI67/DCVAb90QQUGp2Avj8tBhc1wBSu6TZbSdiwxlzsCZ3bG8BGDlgDMWAe0Dz6ebKH6vz7U1yhfuqycM=,iv:cYNkERFqk8e/ynh2yGmgciI+TVe1i8wITLwQE/4JJxo=,tag:80EvQb2tyXw6aFTjtO/dpQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
