apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "localnet",
          "mac": "02:03:04:05:06:07",
          "interface": "myiface1",
          "ips": [
            "192.168.6.120/26"
            ]
        }
      ]'
  name: tinypod3
  namespace: home-assistant
spec:
  containers:
  - args:
    - pause
    image: k8s.gcr.io/e2e-test-images/agnhost:2.36
    imagePullPolicy: IfNotPresent
    name: agnhost-container