kind: ServiceAccount
apiVersion: v1
metadata:
  name: recovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recovery-scc
subjects:
  - kind: ServiceAccount
    name: recovery
    namespace: ${MY_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid # TBD what is min to mount NFS?
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: recovery-pod
spec:
  containers:
  - image: postgres:latest
    imagePullPolicy: Always
    name: main
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    env:
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          key: host
          name: &secret ${MY_NAMESPACE}-db-superuser
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          key: port
          name: *secret
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: dbname
          name: *secret
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: *secret
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: username
          name: *secret
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
    volumeMounts:
    - mountPath: /backup
      name: backup
  serviceAccount: recovery
  volumes:
  - name: backup
    nfs:
      path: /volume1/kubernetes/backup/db/authentik
      server: nas.home.angelnu.com
