- name: Cluster {{ cluster.key }} - Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755 # For some reason, item.mode converts 0755 into 493 ... weird
  loop:
    - clusters/{{ cluster.key }}

- name: Cluster {{ cluster.key }} - Create openshift-install configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  vars:
    cluster_id: "{{ cluster.key }}"
    cluster: "{{ cluster.value }}"
    ssh_pub_key: "{{ ssh_pub_key_task.stdout }}"
    pull_secret: "{{ lookup('file', './files/pull_secret.txt', errors='ignore') }}"
  with_items:
    - {
        src: templates/install-config.yaml.j2,
        dest: "clusters/{{ cluster.key }}/install-config.yaml",
      }
    - {
        src: templates/agent-config.yaml.j2,
        dest: "clusters/{{ cluster.key }}/agent-config.yaml",
      }
  register: okd_installer_config_files

# Let's create the proper OKD installation files (ignition, manifests, ...)
- name: Cluster {{ cluster.key }} - Run openshift-installer
  when: okd_installer_config_files.changed
  shell: |
    cd clusters/{{ cluster.key }}
    rm -rf {{ item.prefix }}-install-dir
    mkdir {{ item.prefix }}-install-dir
    cp install-config.yaml agent-config.yaml {{ item.prefix }}-install-dir
    openshift-install agent create {{ item.cmd }} --dir={{ item.prefix }}-install-dir
  environment:
    PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
  loop:
    - { cmd: "image", prefix: "iso" }
    - { cmd: "pxe-files", prefix: "ipxe" }
  register: installer_task

# Make these files available on the Web server
- name: Cluster {{ cluster.key }} - Copy boot-artifacts to www directory
  when: installer_task.changed
  become: true
  shell: |
    rm -rf /var/www/html/{{ cluster.key }}
    cp -R clusters/{{ cluster.key }}/ipxe-install-dir/boot-artifacts /var/www/html/{{ cluster.key }}
    cp clusters/{{ cluster.key }}/iso-install-dir/agent.x86_64.iso /var/www/html/{{ cluster.key }}/
    chmod -R 755 /var/www/html/{{ cluster.key }}
