apiVersion: v1
kind: Secret
metadata:
  name: dnsmadeeasy
  namespace: cert-manager
stringData:
  key: ENC[AES256_GCM,data:iBbQb412r7qc7qmKtzmYYQpMjv/Qr9pdFKtdgooevWhuWF4v,iv:qzYkULLBecx1C4klzZHZdyO+FIpPC/jx/8Dt92xJwXM=,tag:aHgqfGRJgHUHvVsewe/drw==,type:str]
  secret: ENC[AES256_GCM,data:Vt/zxobJiXc1MR95VbeFzjmZWuqihHW5e99CU5XS5iz/qmvL,iv:GSDMuX7DefZViFyvmfPYFLh7BHV3WadKQLfD6n2jdLg=,tag:Wc76Ic8iRfKHJWlHv7Jk/w==,type:str]
sops:
  age:
    - recipient: age1wdapsm2nw9pr0nmak892gqwat44uhay7d7z5fqtwgsmm6ecatggsfql3yx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUzVmaCtITEtwRlAzU1Z0
        d1VTbTY2SUdsRkpHenAvanRLRUh3MlJMeHdFCmJnbzVVMWlWdkwzalZ0SEFnbDFK
        Qm9KYWFXZGpNdmE0aS91b1RUKy9uS3MKLS0tIDVvdDh6a2RWbXZ1czRKN01vQUlY
        d1FNei94bFYxdzM2MUxOMUtudzY0d2cKgZhQ1SEVwGVFqd4kjPfJXPUDrG58jdoT
        UqmR+5moCSBOZByLxCa5ZNMWUzU9xAer1VoitQZ5BF5G0H+yRpn5+A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age19zycawkart4t4l7a238w0n2w0rmw6anjadwv9yr3ce3js4dz3dcqqgkvsw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbWtlUWdieHhmYWZRbTdS
        Tk9jN3lqOHhwUTdveVMvQitydW84cFdJMUVFCjNqcWJSaVlPcTlHWW13WnZCVHFs
        Qk45b3VyeTE4ZFRPTGpibWZaMVphWEkKLS0tIFdqYmFqSks3NzB2TVRoOEtIdnk0
        Y1Q1dmsyNnR4dVFUa3pya0o4QW55d3MKMmONqO3Hujp6v4K8QkIu0PoVKaPFQ9mm
        bIT7XCB8HhRAmjpGT0267qTNUaLHzcbpPmk2CeRLVUKcXXK1YNEE3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2021-02-14T00:35:45Z"
  mac: ENC[AES256_GCM,data:T7E03Lq3zWu10aZV31xbDYFcNbbe24rhooiUP/3Ir1t3lbzh0VC1Yj1R/Fk1mIpNt7rPrkOPjEZMO86ek0cQI+zOc6o9mZSE9OlVa4KaVpxxFr5qvWe3Yyvqqczuwkx9eD03msQlyBIxFBK08OYfdTOzDUZSHI2AJwErxIN2sd4=,iv:gQMgpYuIiwU3UyYeBBdslXsG4Tq8jDvfEdhS891aokU=,tag:0bIxdzxojcixJLBR3z772Q==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.6.1
